### PR TITLE
Swift 4 support

### PR DESCRIPTION
**Pull request by weiran**
Also fixed a bug where mixed title text attributes were being overwritten with the unfolded value.

### CODE REVIEW

**Comment by 350541732** [comment]
@weiran  作者并没有同步到swift4吧？ 大神请指教一下可以吗

**Comment by Draveness** [comment]
ci failed

**Comment by weiran** [comment]
Not sure why the CI is failing to build, will try again with Xcode 9.3 updates.

**Comment by Draveness** [comment]
👍

**Pull request merged**
